"use client";

import React, { useState, useEffect, useCallback } from "react";
import type { ToolDef } from "../registry";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { CodeEditor } from "@/components/ui/code-editor";
import { motion } from "framer-motion";

export function GitignoreGeneratorTool({ tool }: { tool: ToolDef }) {
  const [availableTemplates, setAvailableTemplates] = useState<string[]>([]);
  const [selectedTemplates, setSelectedTemplates] = useState<string[]>([]);
  const [search, setSearch] = useState("");
  const [loadingList, setLoadingList] = useState(false);
  const [loadingOutput, setLoadingOutput] = useState(false);
  const [output, setOutput] = useState("");
  const [error, setError] = useState<string | null>(null);
  const [copied, setCopied] = useState(false);

  useEffect(() => {
    let isMounted = true;
    setLoadingList(true);
    fetch("https://www.toptal.com/developers/gitignore/api/list")
      .then((res) => res.text())
      .then((text) => {
        if (!isMounted) return;
        // The API returns a newline-separated list of comma-separated items
        const rawItems = text.replace(/\n/g, ",").split(",");
        const cleanItems = rawItems.map((i) => i.trim()).filter(Boolean);
        setAvailableTemplates(cleanItems);
        setLoadingList(false);
      })
      .catch(() => {
        if (isMounted) {
          setError("Failed to load templates. Please check your connection.");
          setLoadingList(false);
        }
      });
    return () => {
      isMounted = false;
    };
  }, []);

  const generate = useCallback(async () => {
    if (selectedTemplates.length === 0) {
      setOutput("");
      return;
    }
    setLoadingOutput(true);
    setError(null);
    try {
      const param = selectedTemplates.join(",");
      const res = await fetch(`https://www.toptal.com/developers/gitignore/api/${param}`);
      if (!res.ok) throw new Error("Failed to fetch gitignore");
      let text = await res.text();
      
      // Clean up the toptal comments and add our own
      text = text.replace(/# Created by https:\/\/www\.toptal\.com[^\n]*\n/g, "");
      text = text.replace(/# Edit at https:\/\/www\.toptal\.com[^\n]*\n/g, "");
      text = text.replace(/# End of https:\/\/www\.toptal\.com[^\n]*/g, "");
      
      const header = `# Generated by https://www.toolmate.co.in/tools/gitignore-generator\n\n`;
      const footer = `\n# End of https://www.toolmate.co.in/tools/gitignore-generator\n`;
      
      setOutput(header + text.trim() + footer);
    } catch (err: any) {
      setError(err.message || "Failed to generate gitignore.");
    } finally {
      setLoadingOutput(false);
    }
  }, [selectedTemplates]);

  useEffect(() => {
    generate();
  }, [generate]);

  const toggleTemplate = (template: string) => {
    setSelectedTemplates((prev) =>
      prev.includes(template) ? prev.filter((t) => t !== template) : [...prev, template]
    );
  };

  const copyToClipboard = async () => {
    if (!output) return;
    try {
      await navigator.clipboard.writeText(output);
      setCopied(true);
      setTimeout(() => setCopied(false), 1500);
    } catch {
      setCopied(false);
    }
  };

  const downloadFile = () => {
    if (!output) return;
    const blob = new Blob([output], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = ".gitignore";
    a.click();
    URL.revokeObjectURL(url);
  };

  const filteredTemplates = availableTemplates.filter((t) =>
    t.toLowerCase().includes(search.toLowerCase())
  );

  return (
    <main className="mx-auto max-w-6xl px-4 py-8">
      <div className="mb-6">
        <h1 className="text-2xl font-bold mb-2">.gitignore Generator</h1>
        <p className="text-sm text-[rgb(var(--muted))] max-w-2xl">
          Instantly generate useful <code>.gitignore</code> files for your project by selecting your operating system, IDE, or programming language.
        </p>
      </div>

      {error && (
        <div className="mb-4 rounded-[var(--radius)] border border-[rgba(var(--danger),0.4)] bg-[rgba(var(--danger),0.08)] p-4 text-sm text-red-500 whitespace-pre-wrap font-mono">
          {error}
        </div>
      )}

      <div className="grid gap-6 lg:grid-cols-12">
        {/* Left Col - Selection */}
        <Card className="p-6 lg:col-span-5 flex flex-col h-[600px]">
          <div className="font-medium mb-3">Select Environments</div>
          
          <input
            type="text"
            placeholder="Search environments (e.g. node, react, macos)"
            value={search}
            onChange={(e) => setSearch(e.target.value)}
            className="w-full rounded border p-2 mb-3 bg-[rgb(var(--card-2))] text-sm focus:outline-none focus:border-[rgb(var(--accent))]"
          />

          {/* Selected Pills */}
          <div className="mb-3 flex flex-wrap gap-2">
            {selectedTemplates.map((t) => (
              <span
                key={t}
                onClick={() => toggleTemplate(t)}
                className="cursor-pointer rounded-full bg-[rgba(var(--accent),0.1)] px-3 py-1 text-xs font-medium text-[rgb(var(--accent))] hover:bg-[rgba(var(--danger),0.1)] hover:text-red-500 transition-colors"
                title="Click to remove"
              >
                {t} &times;
              </span>
            ))}
          </div>

          <div className="flex-1 overflow-y-auto border rounded bg-[rgb(var(--card-2))] p-2">
            {loadingList ? (
              <div className="text-sm text-[rgb(var(--muted))] p-2">Loading templates...</div>
            ) : filteredTemplates.length === 0 ? (
              <div className="text-sm text-[rgb(var(--muted))] p-2">No templates found.</div>
            ) : (
              <div className="flex flex-wrap gap-1">
                {filteredTemplates.map((t) => {
                  const isSelected = selectedTemplates.includes(t);
                  return (
                    <button
                      key={t}
                      onClick={() => toggleTemplate(t)}
                      className={`rounded px-2 py-1 text-xs text-left transition-colors ${
                        isSelected
                          ? "bg-[rgb(var(--accent))] text-white font-medium shadow-sm"
                          : "hover:bg-[rgb(var(--card))] text-[rgb(var(--fg))] border border-transparent hover:border-[rgb(var(--border))]"
                      }`}
                    >
                      {t}
                    </button>
                  );
                })}
              </div>
            )}
          </div>
        </Card>

        {/* Right Col - Output */}
        <Card className="p-0 lg:col-span-7 flex flex-col h-[600px] overflow-hidden relative">
          <div className="flex items-center justify-between p-4 border-b border-[rgb(var(--border))]">
            <div className="font-medium">
              Output
              {loadingOutput && <span className="ml-2 text-xs text-[rgb(var(--muted))] animate-pulse">Generating...</span>}
            </div>
            <div className="flex gap-2">
              <Button size="sm" variant="secondary" onClick={downloadFile} disabled={!output}>
                Download
              </Button>
              <Button size="sm" variant="secondary" onClick={copyToClipboard} disabled={!output}>
                <motion.span
                  key={copied ? "copied" : "copy"}
                  initial={{ opacity: 0, y: 4 }}
                  animate={{ opacity: 1, y: 0 }}
                  transition={{ duration: 0.2 }}
                >
                  {copied ? "Copied ✓" : "Copy"}
                </motion.span>
              </Button>
            </div>
          </div>
          <div className="flex-1 relative">
            <CodeEditor
              className="absolute inset-0"
              value={output}
              language="shell"
              options={{ readOnly: true }}
            />
          </div>
        </Card>
      </div>
    </main>
  );
}
