"use client";
import { Input } from "@/components/ui/input";

import React, { useState, useEffect, useCallback } from "react";
import type { ToolDef } from "../registry";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { CodeEditor } from "@/components/ui/code-editor";
import { motion, AnimatePresence } from "framer-motion";
import { toast } from "sonner";

export function GitignoreGeneratorTool({ tool }: { tool: ToolDef }) {
  const [availableTemplates, setAvailableTemplates] = useState<string[]>([]);
  const [selectedTemplates, setSelectedTemplates] = useState<string[]>([]);
  const [search, setSearch] = useState("");
  const [loadingList, setLoadingList] = useState(false);
  const [loadingOutput, setLoadingOutput] = useState(false);
  const [output, setOutput] = useState("");
  const [error, setError] = useState<string | null>(null);
  const [copied, setCopied] = useState(false);

  useEffect(() => {
    let isMounted = true;
    setLoadingList(true);
    fetch("https://www.toptal.com/developers/gitignore/api/list")
      .then((res) => res.text())
      .then((text) => {
        if (!isMounted) return;
        // The API returns a newline-separated list of comma-separated items
        const rawItems = text.replace(/\n/g, ",").split(",");
        const cleanItems = rawItems.map((i) => i.trim()).filter(Boolean);
        setAvailableTemplates(cleanItems);
        setLoadingList(false);
      })
      .catch(() => {
        if (isMounted) {
          setError("Failed to load templates. Please check your connection.");
          setLoadingList(false);
        }
      });
    return () => {
      isMounted = false;
    };
  }, []);

  const generate = useCallback(async () => {
    if (selectedTemplates.length === 0) {
      setOutput("");
      return;
    }
    setLoadingOutput(true);
    setError(null);
    try {
      const param = selectedTemplates.join(",");
      const res = await fetch(`https://www.toptal.com/developers/gitignore/api/${param}`);
      if (!res.ok) throw new Error("Failed to fetch gitignore");
      let text = await res.text();
      
      // Clean up the toptal comments and add our own
      text = text.replace(/# Created by https:\/\/www\.toptal\.com[^\n]*\n/g, "");
      text = text.replace(/# Edit at https:\/\/www\.toptal\.com[^\n]*\n/g, "");
      text = text.replace(/# End of https:\/\/www\.toptal\.com[^\n]*/g, "");
      
      const header = `# Generated by https://www.toolmate.co.in/tools/gitignore-generator\n\n`;
      const footer = `\n# End of https://www.toolmate.co.in/tools/gitignore-generator\n`;
      
      setOutput(header + text.trim() + footer);
    } catch (err: any) {
      setError(err.message || "Failed to generate gitignore.");
    } finally {
      setLoadingOutput(false);
    }
  }, [selectedTemplates]);

  useEffect(() => {
    generate();
  }, [generate]);

  const toggleTemplate = (template: string) => {
    setSelectedTemplates((prev) =>
      prev.includes(template) ? prev.filter((t) => t !== template) : [...prev, template]
    );
  };

  const copyToClipboard = async () => {
    if (!output) return;
    try {
      await navigator.clipboard.writeText(output);
      toast.success("Copied to clipboard!");
      setCopied(true);
      setTimeout(() => setCopied(false), 1500);
    } catch {
      setCopied(false);
    }
  };

  const downloadFile = () => {
    if (!output) return;
    const blob = new Blob([output], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = ".gitignore";
    a.click();
    URL.revokeObjectURL(url);
  };

  const filteredTemplates = availableTemplates.filter((t) =>
    t.toLowerCase().includes(search.toLowerCase())
  );

  return (
    <div className="w-full">


      {error && (
        <div className="mb-4 rounded-[var(--radius)] border border-[rgba(var(--danger),0.4)] bg-[rgba(var(--danger),0.08)] p-4 text-sm text-red-500 whitespace-pre-wrap font-mono">
          {error}
        </div>
      )}

      <div className="grid gap-6 lg:grid-cols-12">
        {/* Left Col - Selection */}
        <Card className="p-6 lg:col-span-5 flex flex-col h-[600px] border-[rgba(var(--fg),0.1)] shadow-xl shadow-black/5">
          <div className="flex items-center justify-between mb-6">
             <div className="font-extrabold text-lg tracking-tight">Configuration</div>
          </div>
          
          <div className="relative mb-6">
            <div className="absolute inset-y-0 left-0 pl-3.5 flex items-center pointer-events-none">
              <svg className="h-4 w-4 text-[rgb(var(--muted))]" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                 <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z" />
              </svg>
            </div>
            <Input
              type="text"
              placeholder="Search environments (Node, React, macOS...)"
              value={search}
              onChange={(e) => setSearch(e.target.value)}
              className="w-full rounded-xl border border-[rgba(var(--fg),0.1)] py-3 pl-10 pr-4 bg-[rgba(var(--fg),0.02)] text-[14px] font-medium transition-all focus:outline-none focus:ring-2 focus:ring-indigo-500/30 focus:border-indigo-500 hover:bg-[rgba(var(--fg),0.04)] placeholder:text-[rgb(var(--muted))]"
            />
          </div>

          {/* Selected Pills */}
          <AnimatePresence>
            {selectedTemplates.length > 0 && (
              <motion.div 
                initial={{ opacity: 0, height: 0 }}
                animate={{ opacity: 1, height: "auto" }}
                exit={{ opacity: 0, height: 0 }}
                className="mb-6 overflow-hidden"
              >
                <div className="text-[11px] font-bold uppercase tracking-widest text-[rgb(var(--muted))] mb-3">Selected ({selectedTemplates.length})</div>
                <div className="flex flex-wrap gap-2">
                  <AnimatePresence>
                    {selectedTemplates.map((t) => (
                      <motion.button
                        key={t}
                        layout
                        initial={{ opacity: 0, scale: 0.8 }}
                        animate={{ opacity: 1, scale: 1 }}
                        exit={{ opacity: 0, scale: 0.8 }}
                        onClick={() => toggleTemplate(t)}
                        className="group flex items-center gap-1.5 cursor-pointer rounded-lg bg-indigo-500/10 px-3 py-1.5 text-[13px] font-bold text-indigo-500 hover:bg-red-500/10 hover:text-red-500 transition-colors border border-indigo-500/20 hover:border-red-500/20"
                      >
                        {t} 
                        <svg className="w-3.5 h-3.5 opacity-50 group-hover:opacity-100 transition-opacity" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2.5} d="M6 18L18 6M6 6l12 12" /></svg>
                      </motion.button>
                    ))}
                  </AnimatePresence>
                </div>
              </motion.div>
            )}
          </AnimatePresence>

          <div className="flex-1 overflow-y-auto pr-2 relative" style={{ scrollbarWidth: "thin" }}>
            <div className="text-[11px] font-bold uppercase tracking-widest text-[rgb(var(--muted))] mb-3 sticky top-0 bg-[rgb(var(--card))] pb-2 z-10 pt-1">Available Environments</div>
            {loadingList ? (
              <div className="flex items-center justify-center h-32">
                <div className="animate-spin rounded-full h-6 w-6 border-2 border-indigo-500 border-t-transparent"></div>
              </div>
            ) : filteredTemplates.length === 0 ? (
              <div className="text-sm text-[rgb(var(--muted))] p-4 text-center border border-dashed border-[rgba(var(--fg),0.1)] rounded-xl">No environments found.</div>
            ) : (
              <div className="grid grid-cols-2 gap-2 pb-4">
                {filteredTemplates.map((t) => {
                  const isSelected = selectedTemplates.includes(t);
                  return (
                    <Button
                      key={t}
                      onClick={() => toggleTemplate(t)}
                      className={`group flex items-center justify-between rounded-lg px-3 py-2.5 text-[13px] font-medium text-left transition-all ${
                        isSelected
                          ? "bg-indigo-500 text-white shadow-lg shadow-indigo-500/25 ring-1 ring-indigo-500"
                          : "bg-[rgba(var(--fg),0.02)] text-[rgb(var(--fg))] hover:bg-[rgba(var(--fg),0.06)] border border-[rgba(var(--fg),0.05)]"
                      }`}
                    >
                      <span className="truncate pr-2">{t}</span>
                      {isSelected ? (
                        <svg className="w-4 h-4 shrink-0 text-white" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2.5} d="M5 13l4 4L19 7" /></svg>
                      ) : (
                        <svg className="w-4 h-4 shrink-0 opacity-0 group-hover:opacity-40 transition-opacity" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 4v16m8-8H4" /></svg>
                      )}
                    </Button>
                  );
                })}
              </div>
            )}
          </div>
        </Card>

        {/* Right Col - Output */}
        <Card className="p-0 lg:col-span-7 flex flex-col h-[600px] overflow-hidden relative">
          <div className="flex items-center justify-between p-4 border-b border-[rgb(var(--border))]">
            <div className="font-semibold text-[13px] text-[rgb(var(--muted))] uppercase tracking-wider mb-2 ml-1">
              Output
              {loadingOutput && <span className="ml-2 text-xs text-[rgb(var(--muted))] animate-pulse">Generating...</span>}
            </div>
            <div className="flex gap-2">
              <Button size="sm" variant="secondary" onClick={downloadFile} disabled={!output}>
                Download
              </Button>
              <Button size="sm" variant="secondary" onClick={copyToClipboard} disabled={!output}>
                <motion.span
                  key={copied ? "copied" : "copy"}
                  initial={{ opacity: 0, y: 4 }}
                  animate={{ opacity: 1, y: 0 }}
                  transition={{ duration: 0.2 }}
                >
                  {copied ? "Copied ✓" : "Copy"}
                </motion.span>
              </Button>
            </div>
          </div>
          <div className="flex-1 relative">
            <CodeEditor
              className="absolute inset-0"
              value={output}
              language="shell"
              options={{ 
                readOnly: true,
                padding: { top: 0, bottom: 0 }
              }}
            />
          </div>
        </Card>
      </div>
    </div>
  );
}
